version: "3.9"

services:
  accesslog:
    image: diamol/ch09-access-log
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 200M
        reservations:
          cpus: '0.2'
          memory: 50M
    networks:
      - app-net

  iotd:
    image: diamol/ch09-image-of-the-day
    ports:
      - 8088:80
    deploy:
      replicas: 5
      update_config:
        parallelism: 2
        order: start-first
        monitor: 60s
        failure_action: rollback
      rollback_config:
        parallelism: 4
        order: start-first
        failure_action: continue
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
        reservations:
          cpus: '0.2'
          memory: 50M
    networks:
      - app-net

  image-gallery:
    image: diamol/ch09-image-gallery
    ports:
      - 80:80
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
        reservations:
          cpus: '0.2'
          memory: 50M
    networks:
      - app-net

networks:
  app-net:
    name: image-gallery
